AllCops:
  DisplayCopNames: true
  StyleGuideCopsOnly: false
  Exclude:
    - '**/bin/**/*'
    - '**/config/**/*'
    - '**/db/**/*'
    - '**/lib/**/*'
    - '**/log/**/*'
    - '**/storage/**/*'
    - '**/test/**/*'
    - '**/tmp/**/*'
    - '**/vedor/**/'
    - 'Gemfile'
    - 'config.ru'
    - 'Rakefile'


Metrics/LineLength:
  Max: 100

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/Documentation:
  Enabled: false
